import streamlit as st
import time

from transcript import fetch_transcript
from summarizer import generate_summary, extract_key_topics

st.set_page_config(
    page_title="YouTube Study Notes Generator",
    page_icon="📚",
    layout="wide"
)

# Custom CSS
st.markdown("""
<style>
.main-header {
    font-size: 2.5rem;
    font-weight: bold;
    color: #FF0000;
}
.sub-header {
    font-size: 1.2rem;
    color: #666;
}
.metric-card {
    background: #f0f2f6;
    padding: 1rem;
    border-radius: 8px;
    text-align: center;
}
.topic-tag {
    background: #FF4B4B;
    color: white;
    padding: 3px 10px;
    border-radius: 15px;
    margin: 3px;
    display: inline-block;
    font-size: 0.8rem;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-header">📚 YouTube Study Notes Generator</p>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">Powered by Google Gemini Pro + LangChain</p>', unsafe_allow_html=True)
st.divider()

# Sidebar controls
with st.sidebar:
    st.header("⚙️ Settings")
    summary_style = st.selectbox(
        "Summary Style",
        options=["comprehensive", "technical", "interview_prep", "brief"],
        format_func=lambda x: {
            "comprehensive": "📖 Comprehensive Study Notes",
            "technical": "💻 Technical Documentation",
            "interview_prep": "🎯 Interview Preparation",
            "brief": "⚡ Quick Summary"
        }[x]
    )

    st.divider()
    st.markdown("**How it works:**")
    st.markdown("1. Paste a YouTube URL")
    st.markdown("2. Select your summary style")
    st.markdown("3. Get AI-generated study notes")
    st.markdown("4. Download as text file")

    st.divider()
    st.markdown("**Built with:**")
    st.markdown("- Google Gemini Pro")
    st.markdown("- LangChain")
    st.markdown("- YouTube Transcript API")
    st.markdown("- Streamlit")

# Main input
url = st.text_input(
    "🔗 YouTube Video URL",
    placeholder="https://www.youtube.com/watch?v=...",
    help="Paste any YouTube video URL with available captions"
)

col1, col2, col3 = st.columns([1, 1, 1])
with col2:
    generate_btn = st.button("🚀 Generate Study Notes", use_container_width=True, type="primary")

if generate_btn and url:
    # Fetch transcript
    with st.spinner("📥 Fetching video transcript..."):
        try:
            data = fetch_transcript(url)
            st.success("✅ Transcript fetched successfully!")
        except Exception as e:
            st.error(f"❌ Error: {str(e)}")
            st.info("💡 Make sure the video has English captions enabled.")
            st.stop()

    # Show video metrics
    st.subheader("📊 Video Statistics")
    m1, m2, m3 = st.columns(3)
    with m1:
        st.metric("⏱️ Duration", f"{data['duration_minutes']} min")
    with m2:
        st.metric("📝 Word Count", f"{data['word_count']:,}")
    with m3:
        st.metric("🔤 Transcript Segments", f"{data['chunk_count']:,}")
    st.divider()

    # Extract topics
    with st.spinner("🏷️ Identifying key topics..."):
        topics = extract_key_topics(data["transcript"])

    st.subheader("🏷️ Key Topics")
    topics_html = " ".join([f'<span class="topic-tag">{t}</span>' for t in topics])
    st.markdown(topics_html, unsafe_allow_html=True)
    st.divider()

    # Generate summary
    style_names = {
        "comprehensive": "Comprehensive Study Notes",
        "technical": "Technical Documentation",
        "interview_prep": "Interview Preparation Guide",
        "brief": "Quick Summary"
    }

    with st.spinner(f"🤖 Generating {style_names[summary_style]} with Gemini Pro..."):
        start_time = time.time()
        notes = generate_summary(data["transcript"], summary_style)
        elapsed = time.time() - start_time

    st.success(f"✅ Generated in {elapsed:.1f} seconds")
    st.subheader(f"📖 {style_names[summary_style]}")
    st.markdown(notes)
    st.divider()

    # Download options
    st.subheader("💾 Download Notes")
    video_id = data["video_id"]
    download_content = f"""YouTube Study Notes
Generated by YouTube Study Notes Generator (Gemini Pro + LangChain)

Video URL: {url}
Duration: {data['duration_minutes']} minutes
Style: {style_names[summary_style]}
Topics: {', '.join(topics)}

{'='*60}

{notes}

{'='*60}

Generated using Google Gemini Pro API + LangChain
"""

    st.download_button(
        label="📥 Download as .txt",
        data=download_content,
        file_name=f"study_notes_{video_id}.txt",
        mime="text/plain",
        use_container_width=True
    )

elif generate_btn and not url:
    st.warning("⚠️ Please enter a YouTube URL first.")

# Footer
st.divider()
st.markdown(
    "Built by **Varsha Veeramalli** | "
    "[GitHub](https://github.com/varshagupta34) | "
    "Powered by Google Gemini Pro + LangChain"
)